// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxROPIcpOHR1NhheYpgHql22E57AXUC98',
    appId: '1:13768411401:web:3a81f77f811573f0deebd8',
    messagingSenderId: '13768411401',
    projectId: 'quizzapp1stproject',
    authDomain: 'quizzapp1stproject.firebaseapp.com',
    storageBucket: 'quizzapp1stproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-ESL_Cy_qNwJujJl0rzJG0slx_U3lLY',
    appId: '1:13768411401:android:bce7dd126657c795deebd8',
    messagingSenderId: '13768411401',
    projectId: 'quizzapp1stproject',
    storageBucket: 'quizzapp1stproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBhXfMqdVsqCU0A4YRtjgQgkZ7I-0WnE',
    appId: '1:13768411401:ios:f38f53d41b653688deebd8',
    messagingSenderId: '13768411401',
    projectId: 'quizzapp1stproject',
    storageBucket: 'quizzapp1stproject.appspot.com',
    androidClientId: '13768411401-35h0jj65okiiv8ns9933oqcm10bva7mv.apps.googleusercontent.com',
    iosClientId: '13768411401-o7l4o061tv4ihju7s1m4cuu7mtuo66o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBhXfMqdVsqCU0A4YRtjgQgkZ7I-0WnE',
    appId: '1:13768411401:ios:a1a11d91406b7274deebd8',
    messagingSenderId: '13768411401',
    projectId: 'quizzapp1stproject',
    storageBucket: 'quizzapp1stproject.appspot.com',
    androidClientId: '13768411401-35h0jj65okiiv8ns9933oqcm10bva7mv.apps.googleusercontent.com',
    iosClientId: '13768411401-2l6vd6advg1dqnfp6pk80q7ugevv02pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
